# Generated by Django 4.2.6 on 2023-11-05 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('scale_code', models.CharField(max_length=32)),
                ('packing_qty', models.FloatField()),
                ('cost', models.FloatField()),
                ('unit_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('scale_code', models.CharField(max_length=32)),
                ('packing_qty', models.FloatField()),
                ('cost', models.FloatField()),
                ('unit_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bloktoets.store')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('scale_code', models.CharField(max_length=32)),
                ('cost_per_unit', models.FloatField()),
                ('gross_profit', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('ingredients', models.ManyToManyField(related_name='used_in', to='bloktoets.products')),
                ('packaging', models.ManyToManyField(related_name='used_in', to='bloktoets.packaging')),
                ('recipe_book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bloktoets.recipebook')),
                ('recipe_ingredients', models.ManyToManyField(related_name='used_in', to='bloktoets.recipe')),
            ],
        ),
    ]
