# Generated by Django 6.0.4 on 2026-05-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloktoets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='last_received_cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
