# Generated by Django 5.2.1 on 2025-06-03 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloktoets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_book_store',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='bloktoets.store'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, through='bloktoets.Product_relation', through_fields=('recipe', 'ingredient'), to='bloktoets.products'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='packaging',
            field=models.ManyToManyField(blank=True, through='bloktoets.Packaging_relation', through_fields=('recipe', 'ingredient'), to='bloktoets.packaging'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_ingredients',
            field=models.ManyToManyField(blank=True, through='bloktoets.Recipe_relation', through_fields=('recipe', 'ingredient'), to='bloktoets.recipe'),
        ),
        migrations.AddConstraint(
            model_name='packaging',
            constraint=models.UniqueConstraint(fields=('product_code', 'store'), name='packaging_unique_product_code_store'),
        ),
        migrations.AddConstraint(
            model_name='products',
            constraint=models.UniqueConstraint(fields=('product_code', 'store'), name='product_unique_product_code_store'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('product_code', 'recipe_book_store'), name='recipe_unique_product_code_store'),
        ),
    ]
