# Generated by Django 4.2.6 on 2023-11-28 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloktoets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packaging_relation',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in', to='bloktoets.packaging'),
        ),
        migrations.AlterField(
            model_name='packaging_relation',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_packaging', to='bloktoets.recipe'),
        ),
        migrations.AlterField(
            model_name='product_relation',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in', to='bloktoets.products'),
        ),
        migrations.AlterField(
            model_name='product_relation',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_products', to='bloktoets.recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, through='bloktoets.Product_relation', to='bloktoets.products'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='packaging',
            field=models.ManyToManyField(blank=True, through='bloktoets.Packaging_relation', to='bloktoets.packaging'),
        ),
        migrations.AlterField(
            model_name='recipe_relation',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in', to='bloktoets.recipe'),
        ),
        migrations.AlterField(
            model_name='recipe_relation',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_recipes', to='bloktoets.recipe'),
        ),
    ]
