# Generated by Django 6.0.4 on 2026-05-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloktoets', '0002_products_last_received_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='last_saved',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
