# Generated by Django 5.2.1 on 2025-06-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloktoets', '0002_recipe_recipe_book_store_alter_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipe',
            name='recipe_unique_product_code_store',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_book_store',
            new_name='store',
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('product_code', 'store'), name='recipe_unique_product_code_store'),
        ),
    ]
