# Generated by Django 4.2.6 on 2023-11-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloktoets', '0002_alter_packaging_relation_ingredient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_yield',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
