# Generated by Django 5.2.1 on 2025-06-03 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloktoets', '0003_remove_recipe_recipe_unique_product_code_store_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bloktoets.store'),
        ),
    ]
