# Generated by Django 5.2.1 on 2025-06-03 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloktoets', '0004_alter_recipe_store'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='packaging',
            name='packaging_unique_product_code_store',
        ),
        migrations.RemoveConstraint(
            model_name='products',
            name='product_unique_product_code_store',
        ),
        migrations.RemoveConstraint(
            model_name='recipe',
            name='recipe_unique_product_code_store',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='store',
        ),
    ]
