# Generated by Django 4.2.6 on 2023-12-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloktoets', '0005_alter_packaging_stock_on_hand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='stock_on_hand',
            field=models.FloatField(default=0),
        ),
    ]
