# Generated by Django 5.2.5 on 2025-08-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloktoets', '0005_remove_packaging_packaging_unique_product_code_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='unit_of_measure',
            field=models.CharField(default='units', max_length=32),
        ),
    ]
