# Generated by Django 5.2.5 on 2025-09-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloktoets', '0005_remove_packaging_packaging_unique_product_code_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packaging',
            name='supplier_product_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='products',
            name='supplier_product_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='products',
            name='unit_of_measure',
            field=models.CharField(default='unit', max_length=32),
        ),
        migrations.AddField(
            model_name='products',
            name='volume',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
