# Generated by Django 5.2.5 on 2025-10-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloktoets', '0006_packaging_supplier_product_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='unit_of_measure',
            field=models.CharField(default='unit', max_length=32),
        ),
    ]
