# Generated by Django 5.2.5 on 2025-08-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloktoets', '0006_products_unit_of_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='unit_of_measure',
            field=models.CharField(default='unit', max_length=32),
        ),
    ]
