# Generated by Django 4.2.6 on 2024-01-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloktoets', '0006_recipe_stock_on_hand'),
    ]

    operations = [
        migrations.AddField(
            model_name='packaging',
            name='sub_dept',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='sub_dept',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='sub_dept',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
