# Generated by Django 5.2.5 on 2025-12-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloktoets', '0007_recipe_unit_of_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipebook',
            name='packaging_percent',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='unit_of_measure',
            field=models.CharField(default='units', max_length=32),
        ),
    ]
