# Generated by Django 5.2.5 on 2026-03-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloktoets', '0008_recipebook_packaging_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='list_cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
